# Generated by Django 2.0.3 on 2018-03-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='')),
                ('name', models.CharField(default=None, max_length=200)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
